#!/bin/php
<?php

use YonisSavary\Sharp\Classes\CLI\Console;
use YonisSavary\Sharp\Core\Autoloader;

require_once 'vendor/autoload.php';

set_time_limit(0);

Autoloader::$ignoreRequireErrors = true;
Autoloader::initialize();

exit(Console::getInstance()->handleArgv($argv));