#!/bin/php
<?php

use YonisSavary\Sharp\Classes\CLI\Console;
use YonisSavary\Sharp\Core\Autoloader;

$GLOBALS["sharp-root"] = __DIR__;
$GLOBALS["sharp-src"] = realpath(__DIR__ . "/../../src");
$GLOBALS["sharp-autoload-ignore-require-errors"] = true;

require_once '../../vendor/autoload.php';

Autoloader::$ignoreRequireErrors = true;
Autoloader::initialize();

exit(Console::getInstance()->handleArgv($argv));